# Generated by Django 2.2.1 on 2020-06-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_dashboard', '0002_auto_20200528_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
